FROM debian:13.4-slim@sha256:26f98ccd92fd0a44d6928ce8ff8f4921b4d2f535bfa07555ee5d18f61429cf0c AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    megatools unzip && \
    apt-get clean

WORKDIR /pbserver

RUN megadl https://mega.nz/file/mPZSgS4T#3vnm7zR2Tz3ZANt0tnFaorMy4f7j9cpVjgRvMQI0qeo && \
    unzip powerbomberman077c_server.zip && \
    rm powerbomberman077c_server.zip


FROM debian:13.4-slim@sha256:26f98ccd92fd0a44d6928ce8ff8f4921b4d2f535bfa07555ee5d18f61429cf0c AS main

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    mono-devel tmux && \
    apt-get clean

RUN mkdir -p /pbserver

WORKDIR /pbserver

copy --from=builder /pbserver /pbserver/

RUN chmod -R 777 /pbserver/ && \
    chown -R 1000:1000 /pbserver

COPY entrypoint.sh entrypoint.sh

EXPOSE 64640

ENTRYPOINT ["./entrypoint.sh"]
