FROM debian:13.6-slim@sha256:020c0d20b9880058cbe785a9db107156c3c75c2ac944a6aa7ab59f2add76a7bd AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    megatools unzip && \
    apt-get clean

WORKDIR /pbserver

RUN megadl https://mega.nz/file/mPZSgS4T#3vnm7zR2Tz3ZANt0tnFaorMy4f7j9cpVjgRvMQI0qeo && \
    unzip powerbomberman077c_server.zip && \
    rm powerbomberman077c_server.zip


FROM debian:13.6-slim@sha256:020c0d20b9880058cbe785a9db107156c3c75c2ac944a6aa7ab59f2add76a7bd AS main

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    mono-devel tmux && \
    apt-get clean

RUN mkdir -p /pbserver

WORKDIR /pbserver

copy --from=builder /pbserver /pbserver/

RUN chmod -R 777 /pbserver/ && \
    chown -R 1000:1000 /pbserver

COPY entrypoint.sh entrypoint.sh

EXPOSE 64640

ENTRYPOINT ["./entrypoint.sh"]
